language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - python-gflags

install:
  - pip install -r requirements.txt

virtualenv:
  system_site_packages: true
  
# command to run tests
script:
  - nosetests
