language: python
python:
  - "2.7"

install:
  - pip install -U pip
  - pip install python-gflags bibtexparser pypdf2

virtualenv:
  system_site_packages: true
  
# command to run tests
script:
  - nosetests
