language: python
python:
  - "2.7"

install:
  - travis_retry pip install python-gflags bibtexparser pypdf2

virtualenv:
  system_site_packages: true
  
# command to run tests
script:
  - python -m unittest discover tests
